name: firebase_base
description: "Unified base Firebase integration for Flutter applications"
version: 0.1.5
homepage: https://github.com/AlexSeednov/firebase_base
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# Publishable packages can't have 'git' dependencies and because of this
# package depends on non-published application_base it can not be published
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  # Flutter SDK supported versions
  flutter: '>=3.35.4'

  # Dart SDK supported versions
  # https://docs.flutter.dev/release/archive
  sdk: '>=3.9.2'

# Last update - 29.01.2026
dependencies:
  # All platform supported
  application_base:
    git:
      url: https://github.com/AlexSeednov/application_base
      tag_pattern: v{{version}}
    version: ^0.1.6

  # Not supported: Linux | MacOS | Web | Windows
  #
  # Awesome plugins for local notifications
  awesome_notifications: ^0.10.1 # This version is managed by core plugin
  awesome_notifications_core: ^0.10.1

  # Not supported: Linux
  firebase_core: ^4.4.0

  # Not supported: Linux | Web | Windows
  firebase_crashlytics: ^5.0.7

  # Not supported: Linux | Windows
  firebase_messaging: ^16.1.1

  # Base SDK
  flutter:
    sdk: flutter

  # All platform supported
  intl: ^0.20.2

  # All platform supported
  json_annotation: ^4.10.0

  # All platform supported
  rxdart: ^0.28.0

#
dev_dependencies:
  build_runner: ^2.10.5

  #
  flutter_test:
    sdk: flutter

  # dart run build_runner build --delete-conflicting-outputs
  json_serializable: ^6.12.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
